apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nagybalazs89/argo-app-demo-kustomize.git
    targetRevision: HEAD
    path: overlays/dev
    kustomize:
      namePrefix: dev
      commonLabels:
        environment: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true