apiVersion: v1
kind: Service
metadata:
  name: argo-demo-frontend-service
spec:
  selector:
    app: argo-demo
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer